SLStudio.Utils.RemoveHighlighting(get_param('combinedTxRx_ExternalMode', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_combinedTxRx_ExternalMode', 'handle'));
annotate_port('gm_combinedTxRx_ExternalMode/Combined TX and RX/DMA Model Driver', 1, 1, '');
annotate_port('combinedTxRx_ExternalMode/Combined TX and RX/DMA Model Driver', 1, 1, '');
annotate_port('gm_combinedTxRx_ExternalMode/Combined TX and RX/Upsample', 1, 1, '');
annotate_port('combinedTxRx_ExternalMode/Combined TX and RX/Upsample', 1, 1, '');
annotate_port('gm_combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL', 1, 1, '');
annotate_port('combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL', 1, 1, '');
annotate_port('gm_combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL/Packet Generation', 1, 1, '');
annotate_port('combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL/Packet Generation', 1, 1, '');
annotate_port('gm_combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL/Subsystem', 1, 1, '');
annotate_port('combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL/Subsystem', 1, 1, '');
annotate_port('gm_combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL/Subsystem1', 1, 1, '');
annotate_port('combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL/Subsystem1', 1, 1, '');
annotate_port('gm_combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL/Packet Generation/Preamble', 1, 1, '');
annotate_port('combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL/Packet Generation/Preamble', 1, 1, '');
annotate_port('gm_combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL/Packet Generation/Preamble/Delay', 1, 1, '');
annotate_port('combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL/Packet Generation/Preamble/Delay', 1, 1, '');
annotate_port('gm_combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL/Packet Generation/Preamble/PN Sequence For EQ', 1, 1, '');
annotate_port('combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL/Packet Generation/Preamble/PN Sequence For EQ', 1, 1, '');
