open_system('combinedTxRx_ExternalMode');
open_system('gm_combinedTxRx_ExternalMode');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_combinedTxRx_ExternalMode/Combined TX and RX/DMA Model Driver', 'user2');
annotate_port('gm_combinedTxRx_ExternalMode/Combined TX and RX/DMA Model Driver', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('combinedTxRx_ExternalMode/Combined TX and RX/DMA Model Driver', 'user2');
annotate_port('combinedTxRx_ExternalMode/Combined TX and RX/DMA Model Driver', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_combinedTxRx_ExternalMode/Combined TX and RX/Upsample', 'user2');
annotate_port('gm_combinedTxRx_ExternalMode/Combined TX and RX/Upsample', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
hilite_system('combinedTxRx_ExternalMode/Combined TX and RX/Upsample', 'user2');
annotate_port('combinedTxRx_ExternalMode/Combined TX and RX/Upsample', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL', 'user2');
annotate_port('gm_combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
hilite_system('combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL', 'user2');
annotate_port('combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL/Packet Generation', 'user2');
annotate_port('gm_combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL/Packet Generation', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
hilite_system('combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL/Packet Generation', 'user2');
annotate_port('combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL/Packet Generation', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL/Subsystem', 'user2');
annotate_port('gm_combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL/Subsystem', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
hilite_system('combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL/Subsystem', 'user2');
annotate_port('combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL/Subsystem', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL/Subsystem1', 'user2');
annotate_port('gm_combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL/Subsystem1', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
hilite_system('combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL/Subsystem1', 'user2');
annotate_port('combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL/Subsystem1', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL/Packet Generation/Preamble', 'user2');
annotate_port('gm_combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL/Packet Generation/Preamble', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
hilite_system('combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL/Packet Generation/Preamble', 'user2');
annotate_port('combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL/Packet Generation/Preamble', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL/Packet Generation/Preamble/Delay', 'user2');
annotate_port('gm_combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL/Packet Generation/Preamble/Delay', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL/Packet Generation/Preamble/Delay', 'user2');
annotate_port('combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL/Packet Generation/Preamble/Delay', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL/Packet Generation/Preamble/PN Sequence For EQ', 'user2');
annotate_port('gm_combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL/Packet Generation/Preamble/PN Sequence For EQ', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL/Packet Generation/Preamble/PN Sequence For EQ', 'user2');
annotate_port('combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL/Packet Generation/Preamble/PN Sequence For EQ', 1, 1, 'Obstacle to clock-rate pipelining');
