-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\combinedTxRx_ExternalMode\CombinedT_ip_src_Raised_Cosine_Transmit_Filter1.vhd
-- Created: 2018-02-01 13:20:10
-- 
-- Generated by MATLAB 9.3 and HDL Coder 3.11
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: CombinedT_ip_src_Raised_Cosine_Transmit_Filter1
-- Source Path: combinedTxRx_ExternalMode/Combined TX and RX/Transmitter HDL/Raised Cosine Transmit Filter1
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY CombinedT_ip_src_Raised_Cosine_Transmit_Filter1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_1_1                         :   IN    std_logic;
        In1_re                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        In1_im                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        Out1_re                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        Out1_im                           :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
        );
END CombinedT_ip_src_Raised_Cosine_Transmit_Filter1;


ARCHITECTURE rtl OF CombinedT_ip_src_Raised_Cosine_Transmit_Filter1 IS

  -- Component Declarations
  COMPONENT CombinedT_ip_src_FIR_Interpolation
    PORT( clk                             :   IN    std_logic;
          enb_1_1_1                       :   IN    std_logic;
          reset                           :   IN    std_logic;
          CombinedT_ip_src_FIR_Interpolation_in_re :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          CombinedT_ip_src_FIR_Interpolation_in_im :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          CombinedT_ip_src_FIR_Interpolation_out_re :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          CombinedT_ip_src_FIR_Interpolation_out_im :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : CombinedT_ip_src_FIR_Interpolation
    USE ENTITY work.CombinedT_ip_src_FIR_Interpolation(rtl);

  -- Signals
  SIGNAL FIR_Interpolation_out1_re        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL FIR_Interpolation_out1_im        : std_logic_vector(15 DOWNTO 0);  -- ufix16

BEGIN
  u_CombinedT_ip_src_FIR_Interpolation : CombinedT_ip_src_FIR_Interpolation
    PORT MAP( clk => clk,
              enb_1_1_1 => enb_1_1_1,
              reset => reset,
              CombinedT_ip_src_FIR_Interpolation_in_re => In1_re,  -- sfix16_En15
              CombinedT_ip_src_FIR_Interpolation_in_im => In1_im,  -- sfix16_En15
              CombinedT_ip_src_FIR_Interpolation_out_re => FIR_Interpolation_out1_re,  -- sfix16_En14
              CombinedT_ip_src_FIR_Interpolation_out_im => FIR_Interpolation_out1_im  -- sfix16_En14
              );

  Out1_re <= FIR_Interpolation_out1_re;

  Out1_im <= FIR_Interpolation_out1_im;

END rtl;

