-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\combinedTxRx_StandardIQ\CombinedT_ip_src_BranchMetric.vhd
-- Created: 2018-02-01 11:49:53
-- 
-- Generated by MATLAB 9.3 and HDL Coder 3.11
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: CombinedT_ip_src_BranchMetric
-- Source Path: combinedTxRx_StandardIQ/Combined TX and RX/Receiver HDL/Viterbi Decode/Viterbi Decoder/BranchMetric
-- Hierarchy Level: 4
-- 
-- Branch Metric Computation
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.CombinedT_ip_src_Combined_TX_and_RX_pkg.ALL;

ENTITY CombinedT_ip_src_BranchMetric IS
  PORT( din                               :   IN    std_logic_vector(0 TO 1);  -- boolean [2]
        bMet                              :   OUT   vector_of_std_logic_vector2(0 TO 3)  -- ufix2 [4]
        );
END CombinedT_ip_src_BranchMetric;


ARCHITECTURE rtl OF CombinedT_ip_src_BranchMetric IS

  -- Signals
  SIGNAL din_1                            : std_logic;
  SIGNAL din_0                            : std_logic;
  SIGNAL BMet_adders_add_cast             : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL BMet_adders_add_cast_1           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL bMet_entry1                      : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL nsDecmax                         : std_logic;
  SIGNAL maxsubin2                        : std_logic;
  SIGNAL BMet_adders_add_cast_2           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL BMet_adders_add_cast_3           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL bMet_entry2                      : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL maxsubin1                        : std_logic;
  SIGNAL BMet_adders_add_cast_4           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL BMet_adders_add_cast_5           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL bMet_entry3                      : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL BMet_adders_add_cast_6           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL BMet_adders_add_cast_7           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL bMet_entry4                      : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL bMet_tmp                         : vector_of_unsigned2(0 TO 3);  -- ufix2 [4]

BEGIN
  din_1 <= din(1);

  din_0 <= din(0);

  BMet_adders_add_cast <= '0' & din_1;
  BMet_adders_add_cast_1 <= '0' & din_0;
  bMet_entry1 <= BMet_adders_add_cast + BMet_adders_add_cast_1;

  -- Max value of nsDec data type
  nsDecmax <= '1';

  maxsubin2 <= nsDecmax XOR din_1;

  BMet_adders_add_cast_2 <= '0' & maxsubin2;
  BMet_adders_add_cast_3 <= '0' & din_0;
  bMet_entry2 <= BMet_adders_add_cast_2 + BMet_adders_add_cast_3;

  maxsubin1 <= nsDecmax XOR din_0;

  BMet_adders_add_cast_4 <= '0' & din_1;
  BMet_adders_add_cast_5 <= '0' & maxsubin1;
  bMet_entry3 <= BMet_adders_add_cast_4 + BMet_adders_add_cast_5;

  BMet_adders_add_cast_6 <= '0' & maxsubin2;
  BMet_adders_add_cast_7 <= '0' & maxsubin1;
  bMet_entry4 <= BMet_adders_add_cast_6 + BMet_adders_add_cast_7;

  bMet_tmp(0) <= bMet_entry1;
  bMet_tmp(1) <= bMet_entry2;
  bMet_tmp(2) <= bMet_entry3;
  bMet_tmp(3) <= bMet_entry4;

  outputgen: FOR k IN 0 TO 3 GENERATE
    bMet(k) <= std_logic_vector(bMet_tmp(k));
  END GENERATE;

END rtl;

