-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\combinedTxRx_StandardIQ\CombinedT_ip_src_MATLAB_Function1.vhd
-- Created: 2018-02-01 11:49:53
-- 
-- Generated by MATLAB 9.3 and HDL Coder 3.11
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: CombinedT_ip_src_MATLAB_Function1
-- Source Path: combinedTxRx_StandardIQ/Combined TX and RX/Receiver HDL/Viterbi Decode/Buffer/MATLAB Function1
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY CombinedT_ip_src_MATLAB_Function1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        packetLen                         :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        valid                             :   IN    std_logic;
        crcStart                          :   IN    std_logic;
        enablePop                         :   OUT   std_logic;
        validOut                          :   OUT   std_logic;
        viterbiReset                      :   OUT   std_logic;
        crcOut                            :   OUT   std_logic
        );
END CombinedT_ip_src_MATLAB_Function1;


ARCHITECTURE rtl OF CombinedT_ip_src_MATLAB_Function1 IS

  -- Signals
  SIGNAL packetLen_unsigned               : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL currentBitsInBuffer              : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL currentBitsInBuffer_next         : unsigned(15 DOWNTO 0);  -- uint16

BEGIN
  packetLen_unsigned <= unsigned(packetLen);

  RxTxFixedPointLibrary_c2_MATLAB_Function1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      currentBitsInBuffer <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        currentBitsInBuffer <= currentBitsInBuffer_next;
      END IF;
    END IF;
  END PROCESS RxTxFixedPointLibrary_c2_MATLAB_Function1_process;

  RxTxFixedPointLibrary_c2_MATLAB_Function1_output : PROCESS (packetLen_unsigned, valid, crcStart, currentBitsInBuffer)
    VARIABLE sub_cast : signed(16 DOWNTO 0);
    VARIABLE sub_temp : signed(16 DOWNTO 0);
    VARIABLE sub_cast_0 : signed(16 DOWNTO 0);
    VARIABLE sub_temp_0 : signed(16 DOWNTO 0);
    VARIABLE sub_cast_1 : signed(16 DOWNTO 0);
    VARIABLE sub_temp_1 : signed(16 DOWNTO 0);
    VARIABLE add_temp : unsigned(16 DOWNTO 0);
  BEGIN
    currentBitsInBuffer_next <= currentBitsInBuffer;
    --bitsPerCycleDouble = uint16(4);
    IF currentBitsInBuffer > to_unsigned(16#00000044#, 16) THEN 
      sub_cast := signed(resize(currentBitsInBuffer, 17));
      sub_temp := sub_cast - to_signed(16#00002#, 17);
      IF sub_temp(16) = '1' THEN 
        currentBitsInBuffer_next <= X"0000";
      ELSE 
        currentBitsInBuffer_next <= unsigned(sub_temp(15 DOWNTO 0));
      END IF;
      enablePop <= '1';
      viterbiReset <= '0';
      crcOut <= '0';
      validOut <= '1';
      -- Trigger packet at length of packet data and let Viterbi eat remaining
      -- data needed for traceback
    ELSIF currentBitsInBuffer = to_unsigned(16#00000044#, 16) THEN 
      sub_cast_0 := signed(resize(currentBitsInBuffer, 17));
      sub_temp_0 := sub_cast_0 - to_signed(16#00002#, 17);
      IF sub_temp_0(16) = '1' THEN 
        currentBitsInBuffer_next <= X"0000";
      ELSE 
        currentBitsInBuffer_next <= unsigned(sub_temp_0(15 DOWNTO 0));
      END IF;
      enablePop <= '1';
      viterbiReset <= '0';
      crcOut <= '1';
      validOut <= '0';
      -- Flush remaining buffered data
    ELSIF (currentBitsInBuffer < to_unsigned(16#00000044#, 16)) AND (currentBitsInBuffer > to_unsigned(16#00000000#, 16)) THEN 
      sub_cast_1 := signed(resize(currentBitsInBuffer, 17));
      sub_temp_1 := sub_cast_1 - to_signed(16#00002#, 17);
      IF sub_temp_1(16) = '1' THEN 
        currentBitsInBuffer_next <= X"0000";
      ELSE 
        currentBitsInBuffer_next <= unsigned(sub_temp_1(15 DOWNTO 0));
      END IF;
      enablePop <= '1';
      viterbiReset <= '0';
      crcOut <= '0';
      validOut <= '0';
    ELSIF valid = '1' THEN 
      IF crcStart = '1' THEN 
        add_temp := resize(packetLen_unsigned, 17) + to_unsigned(16#00044#, 17);
        IF add_temp(16) /= '0' THEN 
          currentBitsInBuffer_next <= X"FFFF";
        ELSE 
          currentBitsInBuffer_next <= add_temp(15 DOWNTO 0);
        END IF;
        --bitsPerCycleDouble;
        enablePop <= '1';
        viterbiReset <= '1';
        crcOut <= '0';
        validOut <= '1';
      ELSE 
        enablePop <= '0';
        viterbiReset <= '0';
        crcOut <= '0';
        validOut <= '0';
      END IF;
    ELSE 
      enablePop <= '0';
      viterbiReset <= '0';
      crcOut <= '0';
      validOut <= '0';
    END IF;
  END PROCESS RxTxFixedPointLibrary_c2_MATLAB_Function1_output;


END rtl;

