-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\combinedTxRx_StandardIQ\CombinedT_ip_src_DMA_Interface_block.vhd
-- Created: 2018-02-01 11:49:53
-- 
-- Generated by MATLAB 9.3 and HDL Coder 3.11
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: CombinedT_ip_src_DMA_Interface_block
-- Source Path: combinedTxRx_StandardIQ/Combined TX and RX/Transmitter HDL/DMA Interface
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY CombinedT_ip_src_DMA_Interface_block IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_4_0                         :   IN    std_logic;
        byteIn                            :   IN    std_logic_vector(63 DOWNTO 0);  -- ufix64
        validIn                           :   IN    std_logic;
        EOF                               :   IN    std_logic;
        validOut                          :   OUT   std_logic;
        bit_rsvd                          :   OUT   std_logic;
        payloadLength                     :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        startOut                          :   OUT   std_logic;
        readyForMore                      :   OUT   std_logic
        );
END CombinedT_ip_src_DMA_Interface_block;


ARCHITECTURE rtl OF CombinedT_ip_src_DMA_Interface_block IS

  -- Component Declarations
  COMPONENT CombinedT_ip_src_DMA_Control
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_4_0                       :   IN    std_logic;
          byteIn                          :   IN    std_logic_vector(63 DOWNTO 0);  -- ufix64
          validIn                         :   IN    std_logic;
          EOF                             :   IN    std_logic;
          bitOut                          :   OUT   std_logic;
          validOut                        :   OUT   std_logic;
          startOut                        :   OUT   std_logic;
          payloadLength                   :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          readyForInput                   :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : CombinedT_ip_src_DMA_Control
    USE ENTITY work.CombinedT_ip_src_DMA_Control(rtl);

  -- Signals
  SIGNAL bitOut                           : std_logic;
  SIGNAL startOut_1                       : std_logic;
  SIGNAL payloadLength_tmp                : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL readyForInput                    : std_logic;
  SIGNAL Align_with_data_out1             : std_logic;

BEGIN
  u_DMA_Control : CombinedT_ip_src_DMA_Control
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_4_0 => enb_1_4_0,
              byteIn => byteIn,  -- ufix64
              validIn => validIn,
              EOF => EOF,
              bitOut => bitOut,
              validOut => validOut,
              startOut => startOut_1,
              payloadLength => payloadLength_tmp,  -- uint16
              readyForInput => readyForInput
              );

  Align_with_data_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Align_with_data_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_4_0 = '1' THEN
        Align_with_data_out1 <= startOut_1;
      END IF;
    END IF;
  END PROCESS Align_with_data_process;


  bit_rsvd <= bitOut;

  payloadLength <= payloadLength_tmp;

  startOut <= Align_with_data_out1;

  readyForMore <= readyForInput;

END rtl;

