-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\combinedTxRx_StandardIQ\CombinedT_ip_src_HDL_Opt_Complex_FIR4.vhd
-- Created: 2018-02-01 11:49:52
-- 
-- Generated by MATLAB 9.3 and HDL Coder 3.11
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: CombinedT_ip_src_HDL_Opt_Complex_FIR4
-- Source Path: combinedTxRx_StandardIQ/Combined TX and RX/Receiver HDL/Frame Recover/Barker Locate/Measure Phase 
-- Ambiguity/HDL Opt Complex FIR
-- Hierarchy Level: 5
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY CombinedT_ip_src_HDL_Opt_Complex_FIR4 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        In1_re                            :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        In1_im                            :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        validIn                           :   IN    std_logic;
        Out1_re                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- int16
        Out1_im                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- int16
        validOut                          :   OUT   std_logic
        );
END CombinedT_ip_src_HDL_Opt_Complex_FIR4;


ARCHITECTURE rtl OF CombinedT_ip_src_HDL_Opt_Complex_FIR4 IS

  -- Component Declarations
  COMPONENT CombinedT_ip_src_Discrete_FIR_Filter_HDL_Optimized_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
          validIn                         :   IN    std_logic;
          dataOut                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- int16
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT CombinedT_ip_src_Discrete_FIR_Filter_HDL_Optimized1_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
          validIn                         :   IN    std_logic;
          dataOut                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- int16
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT CombinedT_ip_src_Discrete_FIR_Filter_HDL_Optimized2
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
          validIn                         :   IN    std_logic;
          dataOut                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- int16
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT CombinedT_ip_src_Discrete_FIR_Filter_HDL_Optimized3
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
          validIn                         :   IN    std_logic;
          dataOut                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- int16
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : CombinedT_ip_src_Discrete_FIR_Filter_HDL_Optimized_block
    USE ENTITY work.CombinedT_ip_src_Discrete_FIR_Filter_HDL_Optimized_block(rtl);

  FOR ALL : CombinedT_ip_src_Discrete_FIR_Filter_HDL_Optimized1_block
    USE ENTITY work.CombinedT_ip_src_Discrete_FIR_Filter_HDL_Optimized1_block(rtl);

  FOR ALL : CombinedT_ip_src_Discrete_FIR_Filter_HDL_Optimized2
    USE ENTITY work.CombinedT_ip_src_Discrete_FIR_Filter_HDL_Optimized2(rtl);

  FOR ALL : CombinedT_ip_src_Discrete_FIR_Filter_HDL_Optimized3
    USE ENTITY work.CombinedT_ip_src_Discrete_FIR_Filter_HDL_Optimized3(rtl);

  -- Signals
  SIGNAL Discrete_FIR_Filter_HDL_Optimized_out1 : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Discrete_FIR_Filter_HDL_Optimized_out2 : std_logic;
  SIGNAL Discrete_FIR_Filter_HDL_Optimized_out1_signed : signed(15 DOWNTO 0);  -- int16
  SIGNAL Discrete_FIR_Filter_HDL_Optimized1_out1 : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Discrete_FIR_Filter_HDL_Optimized1_out2 : std_logic;
  SIGNAL Discrete_FIR_Filter_HDL_Optimized1_out1_signed : signed(15 DOWNTO 0);  -- int16
  SIGNAL Add_out1                         : signed(15 DOWNTO 0);  -- int16
  SIGNAL Discrete_FIR_Filter_HDL_Optimized2_out1 : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Discrete_FIR_Filter_HDL_Optimized2_out2 : std_logic;
  SIGNAL Discrete_FIR_Filter_HDL_Optimized2_out1_signed : signed(15 DOWNTO 0);  -- int16
  SIGNAL Discrete_FIR_Filter_HDL_Optimized3_out1 : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Discrete_FIR_Filter_HDL_Optimized3_out2 : std_logic;
  SIGNAL Discrete_FIR_Filter_HDL_Optimized3_out1_signed : signed(15 DOWNTO 0);  -- int16
  SIGNAL Subtract_out1                    : signed(15 DOWNTO 0);  -- int16
  SIGNAL Logical_Operator_out1            : std_logic;

BEGIN
  u_Discrete_FIR_Filter_HDL_Optimized : CombinedT_ip_src_Discrete_FIR_Filter_HDL_Optimized_block
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn => In1_re,  -- int16
              validIn => validIn,
              dataOut => Discrete_FIR_Filter_HDL_Optimized_out1,  -- int16
              validOut => Discrete_FIR_Filter_HDL_Optimized_out2
              );

  u_Discrete_FIR_Filter_HDL_Optimized1 : CombinedT_ip_src_Discrete_FIR_Filter_HDL_Optimized1_block
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn => In1_im,  -- int16
              validIn => validIn,
              dataOut => Discrete_FIR_Filter_HDL_Optimized1_out1,  -- int16
              validOut => Discrete_FIR_Filter_HDL_Optimized1_out2
              );

  u_Discrete_FIR_Filter_HDL_Optimized2 : CombinedT_ip_src_Discrete_FIR_Filter_HDL_Optimized2
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn => In1_im,  -- int16
              validIn => validIn,
              dataOut => Discrete_FIR_Filter_HDL_Optimized2_out1,  -- int16
              validOut => Discrete_FIR_Filter_HDL_Optimized2_out2
              );

  u_Discrete_FIR_Filter_HDL_Optimized3 : CombinedT_ip_src_Discrete_FIR_Filter_HDL_Optimized3
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn => In1_re,  -- int16
              validIn => validIn,
              dataOut => Discrete_FIR_Filter_HDL_Optimized3_out1,  -- int16
              validOut => Discrete_FIR_Filter_HDL_Optimized3_out2
              );

  Discrete_FIR_Filter_HDL_Optimized_out1_signed <= signed(Discrete_FIR_Filter_HDL_Optimized_out1);

  Discrete_FIR_Filter_HDL_Optimized1_out1_signed <= signed(Discrete_FIR_Filter_HDL_Optimized1_out1);

  Add_out1 <= Discrete_FIR_Filter_HDL_Optimized_out1_signed - Discrete_FIR_Filter_HDL_Optimized1_out1_signed;

  Out1_re <= std_logic_vector(Add_out1);

  Discrete_FIR_Filter_HDL_Optimized2_out1_signed <= signed(Discrete_FIR_Filter_HDL_Optimized2_out1);

  Discrete_FIR_Filter_HDL_Optimized3_out1_signed <= signed(Discrete_FIR_Filter_HDL_Optimized3_out1);

  Subtract_out1 <= Discrete_FIR_Filter_HDL_Optimized2_out1_signed + Discrete_FIR_Filter_HDL_Optimized3_out1_signed;

  Out1_im <= std_logic_vector(Subtract_out1);

  Logical_Operator_out1 <= Discrete_FIR_Filter_HDL_Optimized3_out2 AND (Discrete_FIR_Filter_HDL_Optimized2_out2 AND (Discrete_FIR_Filter_HDL_Optimized_out2 AND Discrete_FIR_Filter_HDL_Optimized1_out2));

  validOut <= Logical_Operator_out1;

END rtl;

