-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\combinedTxRx_StandardIQ\CombinedT_ip_src_MATLAB_Function_block1.vhd
-- Created: 2018-02-01 11:49:52
-- 
-- Generated by MATLAB 9.3 and HDL Coder 3.11
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: CombinedT_ip_src_MATLAB_Function_block1
-- Source Path: combinedTxRx_StandardIQ/Combined TX and RX/Receiver HDL/Frame Recover/Gardner Timing Recovery/TED 
-- Lock Detector/MATLAB Functio
-- Hierarchy Level: 5
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY CombinedT_ip_src_MATLAB_Function_block1 IS
  PORT( u                                 :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        y                                 :   OUT   std_logic_vector(15 DOWNTO 0)  -- ufix16_En15
        );
END CombinedT_ip_src_MATLAB_Function_block1;


ARCHITECTURE rtl OF CombinedT_ip_src_MATLAB_Function_block1 IS

  -- Signals
  SIGNAL u_signed                         : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL y_tmp                            : unsigned(15 DOWNTO 0);  -- ufix16_En15

BEGIN
  u_signed <= signed(u);

  
  y_tmp <= X"0000" WHEN u_signed(15) = '1' ELSE
      unsigned(u_signed);

  y <= std_logic_vector(y_tmp);

END rtl;

