open_system('combinedTxRx_StandardIQ');
open_system('gm_combinedTxRx_StandardIQ');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_combinedTxRx_StandardIQ/Combined TX and RX/Upsample1', 'user4');
hilite_system('combinedTxRx_StandardIQ/Combined TX and RX/Upsample1', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_combinedTxRx_StandardIQ/Combined TX and RX/Downsample1', 'user4');
hilite_system('combinedTxRx_StandardIQ/Combined TX and RX/Downsample1', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_combinedTxRx_StandardIQ/Combined TX and RX/DMA Model Driver1', 'user4');
hilite_system('combinedTxRx_StandardIQ/Combined TX and RX/DMA Model Driver1', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_combinedTxRx_StandardIQ/Combined TX and RX/Upsample', 'user4');
hilite_system('combinedTxRx_StandardIQ/Combined TX and RX/Upsample', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_combinedTxRx_StandardIQ/Combined TX and RX/Transmitter HDL', 'user4');
hilite_system('combinedTxRx_StandardIQ/Combined TX and RX/Transmitter HDL', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_combinedTxRx_StandardIQ/Combined TX and RX/Transmitter HDL/DMA Interface', 'user4');
hilite_system('combinedTxRx_StandardIQ/Combined TX and RX/Transmitter HDL/DMA Interface', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_combinedTxRx_StandardIQ/Combined TX and RX/Transmitter HDL/Packet Generation', 'user4');
hilite_system('combinedTxRx_StandardIQ/Combined TX and RX/Transmitter HDL/Packet Generation', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_combinedTxRx_StandardIQ/Combined TX and RX/Transmitter HDL/Subsystem', 'user4');
hilite_system('combinedTxRx_StandardIQ/Combined TX and RX/Transmitter HDL/Subsystem', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_combinedTxRx_StandardIQ/Combined TX and RX/Transmitter HDL/Subsystem1', 'user4');
hilite_system('combinedTxRx_StandardIQ/Combined TX and RX/Transmitter HDL/Subsystem1', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_combinedTxRx_StandardIQ/Combined TX and RX/Transmitter HDL/Delay', 'user4');
hilite_system('combinedTxRx_StandardIQ/Combined TX and RX/Transmitter HDL/Delay', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_combinedTxRx_StandardIQ/Combined TX and RX/Transmitter HDL/Packet Generation/Preamble', 'user4');
hilite_system('combinedTxRx_StandardIQ/Combined TX and RX/Transmitter HDL/Packet Generation/Preamble', 'user4');
